title: The Developer's Toolbox
favicon: https://i.ibb.co/N7DTRLZ/Logo-start2impact.png
logo: https://i.ibb.co/N7DTRLZ/Logo-start2impact.png
lang: it

remote_theme: chrisrhymes/bulma-clean-theme
show_downloads: false

show_sidebar: true

footer_menu: footer_menu
fixed_navbar: bottom

paginate: 5
paginate_path: "/blog/page:num"

social:
  name: Mastermind Sviluppo Web & App - start2impact
  links:
    - https://www.facebook.com/groups/193125725354173

defaults:
  - scope:
      path: ""
    values:
      show_sidebar: true
      layout: page
      hero_height: is-medium
      hero_darken: true
      hero_image: https://i.ibb.co/9n5NrBn/The-Developer-s-Toolbox-banner-background.jpg
      image: https://i.ibb.co/9n5NrBn/The-Developer-s-Toolbox-banner-background.jpg
      author: community
