title: The Developer's Toolbox
url: https://developer.opentoolbox.online
baseurl: ""
favicon: https://i.ibb.co/N7DTRLZ/Logo-start2impact.png
logo: https://i.ibb.co/N7DTRLZ/Logo-start2impact.png
lang: it

repository: opentoolbox/developer

theme: jekyll-theme-opentoolbox

footer_menu: footer_menu

links:
  feedback: https://github.com/opentoolbox/developer/issues
  pull_requests: https://github.com/opentoolbox/developer/pulls
  discussions: https://github.com/opentoolbox/developer/discussions
  source: https://github.com/opentoolbox/developer

# Set plugins here to make it compatible with GitHub pages.
# plugins:
#   - plugin-name-here

social:
  name: Mastermind Sviluppo Web & App - start2impact
  links:
    - https://www.facebook.com/groups/193125725354173

jekyll-mentions:
  base_url: https://github.com

permalink: /posts/:title
paginate: 5
paginate_path: "/blog/page:num"

defaults:
  - scope:
      path: ""
    values:
      layout: page
      author: community
      image: https://i.ibb.co/fdhW1RB/The-Developer-s-Toolbox-Poster.jpg
      banner_image: https://i.ibb.co/9n5NrBn/The-Developer-s-Toolbox-banner-background.jpg
      banner_height: is-medium
      banner_darken: true
  - scope:
      path: "resources/*"
    values:
      layout: resource
      show_sidebar: false
      menubar: main_menu
  - scope:
      path: ""
      type: "posts"
    values:
      show_sidebar: true
      banner_with_image: true
      image: https://i.ibb.co/9n5NrBn/The-Developer-s-Toolbox-banner-background.jpg
      author: community
