title: The Developer's Toolbox
# favicon: /path/to/favicon.ico
lang: it

remote_theme: chrisrhymes/bulma-clean-theme
show_downloads: false

show_sidebar: true
menubar: main_menu

footer_menu: footer_menu
fixed_navbar: bottom

defaults:
  - scope:
      path: ""
    values:
      show_sidebar: true
      menubar: main_menu
      layout: page
      hero_height: is-small
      hero_darken: true
      hero_image: https://i.ibb.co/9n5NrBn/The-Developer-s-Toolbox-banner-background.jpg
