title: The Developer's Toolbox
# favicon: /path/to/favicon.ico
lang: it

remote_theme: chrisrhymes/bulma-clean-theme
show_downloads: false

show_sidebar: true
menubar: main_menu

footer_menu: footer_menu

defaults:
  - scope:
      path: ""
    values:
      show_sidebar: true
      menubar: main_menu
