title: The Developer's Toolbox
favicon: https://i.ibb.co/N7DTRLZ/Logo-start2impact.png
logo: https://i.ibb.co/N7DTRLZ/Logo-start2impact.png
lang: it

incremental: true # Still experimental as of v4.2.0, disable if it leads to build not updating

remote_theme: chrisrhymes/bulma-clean-theme
show_downloads: false

show_sidebar: true

permalink: /:categories/:year/:month/:day/:title

footer_menu: footer_menu
fixed_navbar: bottom

paginate: 5
paginate_path: "/blog/page:num"

# Set plugins here to make it compatible with GitHub pages.
plugins:
  - jekyll-environment-variables
  - jekyll-mentions

social:
  name: Mastermind Sviluppo Web & App - start2impact
  links:
    - https://www.facebook.com/groups/193125725354173

jekyll-mentions:
  base_url: https://github.com

defaults:
  - scope:
      path: ""
    values:
      layout: page
      hero_height: is-medium
      hero_darken: true
      hero_image: https://i.ibb.co/9n5NrBn/The-Developer-s-Toolbox-banner-background.jpg
      author: community
  - scope:
      path: "resources/*"
    values:
      layout: resource
      category: resources
      show_sidebar: false
      menubar: main_menu
      image: https://i.ibb.co/fdhW1RB/The-Developer-s-Toolbox-Poster.jpg
  - scope:
      path: ""
      type: "posts"
    values:
      show_sidebar: true
      use_banner: true
      image: https://i.ibb.co/9n5NrBn/The-Developer-s-Toolbox-banner-background.jpg
      author: community

  # Main categories subdivision
  - scope:
      path: "/resources/android/*"
    values:
      category: android
  - scope:
      path: "/resources/backend/*"
    values:
      category: backend
  - scope:
      path: "/resources/devops/*"
    values:
      category: devops
  - scope:
      path: "/resources/frontend/*"
    values:
      category: frontend
  - scope:
      path: "/resources/hosting/*"
    values:
      category: hosting
  - scope:
      path: "/resources/ios/*"
    values:
      category: ios
